tasks:
  - init: |
      echo '<<<-- init -----' 
      curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.4.3/docker-compose.yaml'
      mkdir -p ./dags ./logs ./plugins
      echo -e "AIRFLOW_UID=$(id -u)" > .env
      echo '----- init -->>>' 
  - command: |
      echo '<<<-- command -----' 
      docker-compose up
      echo '----- command -->>>' 
ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker

